"""empty message

Revision ID: 9f85cd3318fd
Revises: 
Create Date: 2023-08-15 16:38:14.853028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f85cd3318fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('category_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('category_pk'),
    schema='kiosk'
    )
    op.create_table('option_',
    sa.Column('option_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_name', sa.String(length=50), nullable=False),
    sa.Column('option_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('option_pk'),
    schema='kiosk'
    )
    op.create_table('orderer',
    sa.Column('orderer_id', sa.Integer(), nullable=False),
    sa.Column('orderer_name', sa.String(length=50), nullable=False),
    sa.Column('orderer_phone', sa.String(length=50), nullable=False),
    sa.Column('orderer_gender', sa.String(length=10), nullable=False),
    sa.Column('orderer_age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('orderer_id'),
    schema='kiosk'
    )
    op.create_index(op.f('ix_kiosk_orderer_orderer_id'), 'orderer', ['orderer_id'], unique=False, schema='kiosk')
    op.create_table('menu',
    sa.Column('menu_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(length=50), nullable=False),
    sa.Column('menu_price', sa.Integer(), nullable=False),
    sa.Column('menu_description', sa.String(length=50), nullable=False),
    sa.Column('category_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_pk'], ['kiosk.categories.category_pk'], ),
    sa.PrimaryKeyConstraint('menu_pk'),
    schema='kiosk'
    )
    op.create_table('order_detail',
    sa.Column('order_detail_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderer_id', sa.Integer(), nullable=True),
    sa.Column('menu_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_pk'], ['kiosk.menu.menu_pk'], ),
    sa.ForeignKeyConstraint(['orderer_id'], ['kiosk.orderer.orderer_id'], ),
    sa.PrimaryKeyConstraint('order_detail_pk'),
    schema='kiosk'
    )
    op.create_table('recommended_menu',
    sa.Column('rec_menu_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('menu_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_pk'], ['kiosk.menu.menu_pk'], ),
    sa.PrimaryKeyConstraint('rec_menu_pk'),
    schema='kiosk'
    )
    op.create_table('order_option',
    sa.Column('order_detail_pk', sa.Integer(), nullable=True),
    sa.Column('option_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_pk'], ['kiosk.option_.option_pk'], ),
    sa.ForeignKeyConstraint(['order_detail_pk'], ['kiosk.order_detail.order_detail_pk'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_option')
    op.drop_table('recommended_menu', schema='kiosk')
    op.drop_table('order_detail', schema='kiosk')
    op.drop_table('menu', schema='kiosk')
    op.drop_index(op.f('ix_kiosk_orderer_orderer_id'), table_name='orderer', schema='kiosk')
    op.drop_table('orderer', schema='kiosk')
    op.drop_table('option_', schema='kiosk')
    op.drop_table('categories', schema='kiosk')
    op.drop_table('face_analysis')
    # ### end Alembic commands ###
