"""empty message

Revision ID: b7cddbd0869a
Revises: d31160923e83
Create Date: 2023-08-17 16:10:21.466590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7cddbd0869a'
down_revision: Union[str, None] = 'd31160923e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_face_analysis_name', table_name='face_analysis')
    op.create_index(op.f('ix_kiosk_face_analysis_name'), 'face_analysis', ['name'], unique=False, schema='kiosk')
    op.drop_constraint('menu_ibfk_1', 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'categories', ['category_pk'], ['category_pk'], source_schema='kiosk', referent_schema='kiosk')
    op.add_column('order_detail', sa.Column('face_analysis_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_detail_ibfk_2', 'order_detail', type_='foreignkey')
    op.drop_constraint('order_detail_ibfk_1', 'order_detail', type_='foreignkey')
    op.create_foreign_key(None, 'order_detail', 'menu', ['menu_pk'], ['menu_pk'], source_schema='kiosk', referent_schema='kiosk')
    op.create_foreign_key(None, 'order_detail', 'face_analysis', ['face_analysis_id'], ['id'], source_schema='kiosk', referent_schema='kiosk')
    op.drop_column('order_detail', 'orderer_id')
    op.drop_constraint('order_option_ibfk_1', 'order_option', type_='foreignkey')
    op.drop_constraint('order_option_ibfk_2', 'order_option', type_='foreignkey')
    op.create_foreign_key(None, 'order_option', 'option_', ['option_pk'], ['option_pk'], referent_schema='kiosk')
    op.create_foreign_key(None, 'order_option', 'order_detail', ['order_detail_pk'], ['order_detail_pk'], referent_schema='kiosk')
    op.create_index(op.f('ix_kiosk_orderer_orderer_id'), 'orderer', ['orderer_id'], unique=False, schema='kiosk')
    op.drop_constraint('recommended_menu_ibfk_1', 'recommended_menu', type_='foreignkey')
    op.create_foreign_key(None, 'recommended_menu', 'menu', ['menu_pk'], ['menu_pk'], source_schema='kiosk', referent_schema='kiosk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommended_menu', schema='kiosk', type_='foreignkey')
    op.create_foreign_key('recommended_menu_ibfk_1', 'recommended_menu', 'menu', ['menu_pk'], ['menu_pk'])
    op.drop_index(op.f('ix_kiosk_orderer_orderer_id'), table_name='orderer', schema='kiosk')
    op.drop_constraint(None, 'order_option', type_='foreignkey')
    op.drop_constraint(None, 'order_option', type_='foreignkey')
    op.create_foreign_key('order_option_ibfk_2', 'order_option', 'option_', ['option_pk'], ['option_pk'])
    op.create_foreign_key('order_option_ibfk_1', 'order_option', 'order_detail', ['order_detail_pk'], ['order_detail_pk'])
    op.add_column('order_detail', sa.Column('orderer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_detail', schema='kiosk', type_='foreignkey')
    op.drop_constraint(None, 'order_detail', schema='kiosk', type_='foreignkey')
    op.create_foreign_key('order_detail_ibfk_1', 'order_detail', 'menu', ['menu_pk'], ['menu_pk'])
    op.create_foreign_key('order_detail_ibfk_2', 'order_detail', 'orderer', ['orderer_id'], ['orderer_id'])
    op.drop_column('order_detail', 'face_analysis_id')
    op.drop_constraint(None, 'menu', schema='kiosk', type_='foreignkey')
    op.create_foreign_key('menu_ibfk_1', 'menu', 'categories', ['category_pk'], ['category_pk'])
    op.drop_index(op.f('ix_kiosk_face_analysis_name'), table_name='face_analysis', schema='kiosk')
    op.create_index('ix_face_analysis_name', 'face_analysis', ['name'], unique=False)
    # ### end Alembic commands ###
