"""empty message

Revision ID: d31160923e83
Revises: 9f85cd3318fd
Create Date: 2023-08-17 15:23:58.660993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31160923e83'
down_revision: Union[str, None] = '9f85cd3318fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_analysis', sa.Column('name', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_face_analysis_name'), 'face_analysis', ['name'], unique=False)
    op.drop_constraint('menu_ibfk_1', 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'categories', ['category_pk'], ['category_pk'], source_schema='kiosk', referent_schema='kiosk')
    op.drop_constraint('order_detail_ibfk_1', 'order_detail', type_='foreignkey')
    op.drop_constraint('order_detail_ibfk_2', 'order_detail', type_='foreignkey')
    op.create_foreign_key(None, 'order_detail', 'menu', ['menu_pk'], ['menu_pk'], source_schema='kiosk', referent_schema='kiosk')
    op.create_foreign_key(None, 'order_detail', 'orderer', ['orderer_id'], ['orderer_id'], source_schema='kiosk', referent_schema='kiosk')
    op.drop_constraint('order_option_ibfk_2', 'order_option', type_='foreignkey')
    op.drop_constraint('order_option_ibfk_1', 'order_option', type_='foreignkey')
    op.create_foreign_key(None, 'order_option', 'order_detail', ['order_detail_pk'], ['order_detail_pk'], referent_schema='kiosk')
    op.create_foreign_key(None, 'order_option', 'option_', ['option_pk'], ['option_pk'], referent_schema='kiosk')
    op.drop_constraint('recommended_menu_ibfk_1', 'recommended_menu', type_='foreignkey')
    op.create_foreign_key(None, 'recommended_menu', 'menu', ['menu_pk'], ['menu_pk'], source_schema='kiosk', referent_schema='kiosk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommended_menu', schema='kiosk', type_='foreignkey')
    op.create_foreign_key('recommended_menu_ibfk_1', 'recommended_menu', 'menu', ['menu_pk'], ['menu_pk'])
    op.drop_constraint(None, 'order_option', type_='foreignkey')
    op.drop_constraint(None, 'order_option', type_='foreignkey')
    op.create_foreign_key('order_option_ibfk_1', 'order_option', 'option_', ['option_pk'], ['option_pk'])
    op.create_foreign_key('order_option_ibfk_2', 'order_option', 'order_detail', ['order_detail_pk'], ['order_detail_pk'])
    op.drop_constraint(None, 'order_detail', schema='kiosk', type_='foreignkey')
    op.drop_constraint(None, 'order_detail', schema='kiosk', type_='foreignkey')
    op.create_foreign_key('order_detail_ibfk_2', 'order_detail', 'orderer', ['orderer_id'], ['orderer_id'])
    op.create_foreign_key('order_detail_ibfk_1', 'order_detail', 'menu', ['menu_pk'], ['menu_pk'])
    op.drop_constraint(None, 'menu', schema='kiosk', type_='foreignkey')
    op.create_foreign_key('menu_ibfk_1', 'menu', 'categories', ['category_pk'], ['category_pk'])
    op.drop_index(op.f('ix_face_analysis_name'), table_name='face_analysis')
    op.drop_column('face_analysis', 'name')
    # ### end Alembic commands ###
